#ifndef COMPOUND_CONST_H
# define COMPOUND_CONST_H

# define INT32_DIGITS_DEC  10
# define INT32_DIGITS_HEX  8

# define INT64_DIGITS_DEC  19
# define INT64_DIGITS_HEX  16


// # define UINT32_DIGITS_DEC  10
// # define UINT32_DIGITS_HEX  

// # define UINT64_DIGITS_DEC  20
// # define UINT64_DIGITS_HEX  16

#endif  /* COMPOUND_CONST_H */
